apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  name: node-app-deployment-memory 
spec:
  maxReplicas: 15
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
