apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      name: nodejs-pod
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/nodejs-test:latest
        ports:
          -  containerPort: 3000
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 150m
          limits:
            memory: "400Mi"
          requests:
            memory: "40Mi" 
        imagePullPolicy: Always
      imagePullSecrets:
      -  name: ecr-registry-key