apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-service
  name: nodejs-service
spec:
  ports:
  - name: 3000-3000
    nodePort: 30080
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-app
  type: NodePort
status:
  loadBalancer: {}